### PR TITLE
refactor: Change Whisper model from 'base' to 'turbo' for improved transcription quality

### PR DESCRIPTION
**Pull request by roku-on-it**
I've changed the Whisper model to Turbo

### CODE REVIEW

**Comment by stephengpope** [comment]
Hi @roku-on-it was curious what made you add this "turbo" mode, I wasn't familiar with it before.

Also, what made you close the issue?

**Comment by roku-on-it** [comment]
Hello Stephen. The reason I closed the issue is because I forgot I opened a PR and just pushed random stuff (sorry about that). And [the turbo model is an optimized version of large-v3 that offers faster transcription speed with a minimal degradation in accuracy.](https://github.com/openai/whisper?tab=readme-ov-file#available-models-and-languages)

And I think the model could be gotten from environment variables and not use hard-coded "base" model.

And the layer that preloads the model in Dockerfile does not actually preloads. It loads the model again upon receiving first request that utilizes any of the AI endpoints.

We needed turbo model because base model couldn't satisfy our needs and generated junk transcriptions.

**Comment by stephengpope** [comment]
Yes, I noticed the pre-load issue as well, that is something I think we can fix.

So would you want to set the Whisper base via ENV var or when you call Whisper.

I think since its 8 gigs it would need to be built into the docker image to be performant.

**Comment by roku-on-it** [comment]
I think it's better to pass the model to `whisper.load()` from ENV var for some models can be big as you said like turbo.

**Pull request closed without merging**
